Añadiendo ness.css y aplicando estilos al html :nail_care: #8
estreamercoders/Homenaje-a-movieFire pull request #12
Opened 2019-03-24 13:01 UTC by Fa-v

Ver #8

2019-03-25 07:03 UTC, carlosazaustre reviewed
Hola @Fa-v ! Genial la Pull-Request :) Buen trabajo!

Solo un detalle, desde la parte de revisión de código. En `app.js` por ejemplo, has hecho varios cambios de linting (posiblemente el editor los ha hecho automáticamente) y cuando se visualiza el *diff* en Github, se marca toda la línea.

En ficheros pequeños no pasa nada, pero si se trata de ficheros grandes y muchos cambios, para la persona que hace el review le aparecen muchos cambios, y es dificil de ver si solo se ha añadido un `;' o se han cambiado más cosas en el código.

Es solo un apunte :)

2019-03-26 17:08 UTC, Fa-v commented
Oh sí! Tienes razón, fue el prettier en mi editor.

2019-03-26 17:40 UTC, carlosazaustre commented
A mí me pasa muy a menudo y no me daba cuenta 😅

2019-03-31 18:00 UTC, UlisesGascon requested changes
Por fa @Fa-v elimina el token. Gracias por el PR^^

2019-03-31 18:00 UTC, UlisesGascon commented on app.js
> +  const url = `http://www.omdbapi.com/?t=${title}&apikey=BANMEPLZ`;
se colo el token

2019-04-01 13:16 UTC, UlisesGascon approved these changes

2019-04-01 13:16 UTC, merged